config/routes.rb
Rails.application.routes.draw do
  root 'urls#index'

  resources 'urls'

  get '/:short_url', to: 'urls#original_url'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord

  validates :original_url, presence: true, uniqueness: true

  after_create :generate_url_shortner

  def generate_url_shortner
    base_62_characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".split('')
    array_of_character = get_url_shortner_ids
    corresponding_short_url = ""
    array_of_character.each do |index|
      corresponding_short_url << base_62_characters[index-1]
    end
    self.update_attribute(:short_url, corresponding_short_url)
  end

  def get_url_shortner_ids
    url_id = self.id
    array_of_id = []
    while url_id > 0
      remainder = url_id % 62
      array_of_id << remainder
      url_id = url_id / 62
    end
    array_of_id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
  end

  def create
    @short_url = ShortUrl.new(url_params)
    if @short_url.save
      redirect_to url_path(@short_url)
    else
      redirect_to root_path  
    end
  end

  def show
    
  end

  def original_url
    corresponding_short_url = params[:short_url]
    url = ShortUrl.find_by(short_url: corresponding_short_url)
    redirect_to "https://#{url.original_url}"
  end

  private
    def url_params
      params.require(:short_url).permit(:original_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper

  def get_short_url
    ShortUrl.last
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/index.html.erb
<h1>Welcome!!</h1>
<p>
  Please Enter the Url
</p>
<%= form_for :short_url, url: urls_path do |f| %>
  <%= f.label :original_url %>
  <%= f.text_field :original_url %>

  <%= f.submit "Create Shortner" %>
<% end %>

app/views/urls/show.html.erb
<h1>Url Shortner</h1>
<% short_url = get_short_url %>
<%= link_to "#{short_url.short_url}", "http://localhost:3000/#{short_url.short_url}" %>
<br/>
<%= link_to "Home", root_path %>